/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.jooqtutorial;


import com.baeldung.jooq.introduction.db.jooqtutorial.tables.Author;
import com.baeldung.jooq.introduction.db.jooqtutorial.tables.AuthorBook;
import com.baeldung.jooq.introduction.db.jooqtutorial.tables.Book;


/**
 * Convenience access to all tables in jooqtutorial.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooqtutorial.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>jooqtutorial.author_book</code>.
     */
    public static final AuthorBook AUTHOR_BOOK = AuthorBook.AUTHOR_BOOK;

    /**
     * The table <code>jooqtutorial.book</code>.
     */
    public static final Book BOOK = Book.BOOK;
}
