/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db;


import com.baeldung.jooq.introduction.db.information_schema.InformationSchema;
import com.baeldung.jooq.introduction.db.jooqtutorial.Jooqtutorial;

import java.util.Arrays;
import java.util.List;

import org.jooq.Constants;
import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;
import org.jooq.meta.derby.sys.Sys;
import org.jooq.meta.mysql.mysql.Mysql;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_CATALOG</code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();


    /**
     * The schema <code>information_schema</code>.
     */
    public final InformationSchema INFORMATION_SCHEMA = InformationSchema.INFORMATION_SCHEMA;

    /**
     * The schema <code>jooqtutorial</code>.
     */
    public final Jooqtutorial JOOQTUTORIAL = Jooqtutorial.JOOQTUTORIAL;


    /**
     * The schema <code>mysql</code>.
     */
    public final Mysql MYSQL = Mysql.MYSQL;



    /**
     * The schema <code>sys</code>.
     */
    public final Sys SYS = Sys.SYS;


    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        return Arrays.asList(

            InformationSchema.INFORMATION_SCHEMA,
            Jooqtutorial.JOOQTUTORIAL,

            Mysql.MYSQL,

            Sys.SYS

        );
    }

    /**
     * A reference to the 3.16 minor release of the code generator. If this
     * doesn't compile, it's because the runtime library uses an older minor
     * release, namely: 3.16. You can turn off the generation of this reference
     * by specifying /configuration/generator/generate/jooqVersionReference
     */
    private static final String REQUIRE_RUNTIME_JOOQ_VERSION = Constants.VERSION_3_16;
}
